# .alacritty.toml

[window]
padding = { x = 5, y = 5 }
dynamic_title = false
opacity = 0.9

[scrolling]
history = 50000

[font]
size = 10
normal = { family = "Fira Code" }

[cursor.style]
shape = "Block"
blinking = "Never"


# Colors: from 256-colors pallete

[colors.primary]
background = "#ffffff" # 231
foreground = "#3a3a3a" # 237

[colors.selection]
text       = "#000000" #   0
background = "#d7d7ff" # 189

[colors.cursor]
text       = "#ffffff" # 230
cursor     = "#8787af" # 103

[colors.normal]
black                 = "#3a3a3a" # 237
red                   = "#af0000" # 124
green                 = "#008700" #  28
yellow                = "#af8700" # 136
blue                  = "#005f87" #  24
magenta               = "#870087" #  90
cyan                  = "#008787" #  30
white                 = "#808080" # 244

# [colors.bright]
# black                 = "#073f4d"
# red                   = "#de3330"
# green                 = "#42a600"
# yellow                = "#dbab05"
# blue                  = "#2377b5"
# magenta               = "#a925bf"
# cyan                  = "#2ba69c"
# white                 = "#a6a195"

# Disable default keybinds

[mouse]
bindings = [
  { mouse = "Middle",  action = "ReceiveChar" },
]

[keyboard]
bindings = [
  { key = "+",  mods = "Control", action = "ReceiveChar" },
  { key = "-",  mods = "Control", action = "ReceiveChar" },
  { key = "=",  mods = "Control", action = "ReceiveChar" },
]

