# .alacritty.toml

[colors.primary]
background = "#fffff7"
foreground = "#404040"

[colors.cursor]
text = '#000000'
cursor = '#bfe0ff'

[keyboard]
bindings = [
 { key = "f", mods = "Control|Alt", action = "ToggleFullscreen" },
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
# decorations = "None"
dynamic_title = false

[scrolling]
history = 50000

[font]
size = 12
normal = { family = "Inconsolata" }

[cursor.style]
shape = "Block"
blinking = "Never"

